#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use DrupalPatchUtils\Command\Configure;
use DrupalPatchUtils\Command\CreateIssue;
use DrupalPatchUtils\Command\Login;
use DrupalPatchUtils\Command\Logout;
use DrupalPatchUtils\Command\PostComment;
use DrupalPatchUtils\Command\SearchIssuePatch;
use DrupalPatchUtils\Command\SearchRtbcPatches;
use DrupalPatchUtils\Command\TagIssue;
use DrupalPatchUtils\Command\ValidatePatch;
use DrupalPatchUtils\Command\ValidateRtbcPatches;
use Symfony\Component\Console\Application;


$application = new Application();
$application->add(new Configure());
$application->add(new PostComment());
$application->add(new CreateIssue());
$application->add(new SearchIssuePatch());
$application->add(new SearchRtbcPatches());
$application->add(new ValidatePatch());
$application->add(new ValidateRtbcPatches());
$application->add(new TagIssue());
$application->add(new Login());
$application->add(new Logout());
$application->run();
